CREATE TABLE BACKUP_TEACHER (
    TEACHER_ID INT NOT NULL,
    TEACHER_NAME VARCHAR(150) NOT NULL,
    TEACHER_EMAIL VARCHAR(150) NOT NULL,
    TEACHER_PHONE VARCHAR(15),
    CONSTRAINT PK_BACKUP_TEACHER PRIMARY KEY (TEACHER_ID)
);
