SELECT
    S.SUBJECT_NAME AS 'SUBJECT',
    S.SUBJECT_CREDITS AS 'CREDITS',
    CASE
        WHEN S.SUBJECT_CREDITS BETWEEN 0 AND 2 THEN 'REGULAR'
        WHEN S.SUBJECT_CREDITS = 3 THEN 'PREREQUISITE'
        WHEN S.SUBJECT_CREDITS >= 4 THEN 'CURRICULAR'
    END AS 'SUBJECT TYPE'
FROM SUBJECT S;

SELECT
    S.SUBJECT_ID AS 'ID_SUBJECT',
    S.SUBJECT_NAME AS 'SUBJECT',
    S.SUBJECT_CREDITS AS 'CREDITS',
    S.SUBJECT_DEPARTMENT AS 'DEPARTMENT',
    T.TEACHER_NAME AS 'TEACHER',
    TS.TEACHER_TYPE AS 'TYPE',
    T.TEACHER_EMAIL AS 'EMAIL'
FROM TEACHER T, SUBJECT S, TEACHERSUBJECT TS
WHERE T.TEACHER_ID = TS.TEACHER_ID
AND S.SUBJECT_ID = TS.SUBJECT_ID
AND T.TEACHER_EMAIL LIKE '%@UNIVERSITY.EDU';