ALTER EVENT PR_INSERT_BACKUPTEACHERS ENABLE;
ALTER EVENT PR_INSERT_BACKUPTEACHERS DISABLE;

CREATE EVENT DO_INSERT_BACKUPTEACHERS
ON SCHEDULE EVERY 1 DAY STARTS '2025-12-08 00:15:00'
DO CALL PR_INSERT_BACKUPTEACHERS();

DELIMITER $$
CREATE PROCEDURE PR_INSERT_BACKUPTEACHERS()
BEGIN
    TRUNCATE TABLE BACKUP_TEACHER;
    INSERT INTO BACKUP_TEACHER SELECT * 
    FROM TEACHER 
    WHERE TEACHER_EMAIL LIKE '%@GMAIL.COM'
    AND TEACHER_PHONE IS NULL;
END;
$$
DELIMITER ;