DELIMITER $$
CREATE TRIGGER TR_INSERT_AUDITSUBJECT 
BEFORE DELETE ON SUBJECT
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_SUBJECT(SUBJECT_ID, SUBJECT_NAME, SUBJECT_CREDITS, SUBJECT_DEPARTMENT)
    VALUES(OLD.SUBJECT_ID, OLD.SUBJECT_NAME, OLD.SUBJECT_CREDITS, OLD.SUBJECT_DEPARTMENT);
END;
$$
DELIMITER ;