-- 🔹 Crear la función que ejecutará la lógica del trigger
CREATE OR REPLACE FUNCTION FN_INSERT_AUDITSUBJECT()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO AUDIT_SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_CREDITS, SUBJECT_DEPARTMENT)
    VALUES (OLD.SUBJECT_ID, OLD.SUBJECT_NAME, OLD.SUBJECT_CREDITS, OLD.SUBJECT_DEPARTMENT);
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- 🔹 Crear el trigger que usará la función
CREATE TRIGGER TR_INSERT_AUDITSUBJECT
BEFORE DELETE ON SUBJECT
FOR EACH ROW
EXECUTE FUNCTION FN_INSERT_AUDITSUBJECT();
