CREATE TABLE TEACHER(
    TEACHER_ID INT NOT NULL AUTO_INCREMENT,
    TEACHER_NAME VARCHAR(150) NOT NULL,
    TEACHER_PHONE VARCHAR(15),
    TEACHER_EMAIL VARCHAR(150) NOT NULL,
    CONSTRAINT PK_TEACHER PRIMARY KEY (TEACHER_ID),
    CONSTRAINT UK_TEACHER_EMAIL UNIQUE (TEACHER_EMAIL)
);

CREATE TABLE SUBJECT(
    SUBJECT_ID INT NOT NULL AUTO_INCREMENT,
    SUBJECT_NAME VARCHAR(150) NOT NULL,
    SUBJECT_CREDITS INT NOT NULL,
    SUBJECT_DEPARTMENT VARCHAR(150),
    CONSTRAINT PK_SUBJECT PRIMARY KEY (SUBJECT_ID)
);

CREATE TABLE TEACHERSUBJECT(
    TEACHER_ID INT,
    SUBJECT_ID INT,
    TEACHER_TYPE VARCHAR(150),
    CONSTRAINT FK_TEACHER FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(TEACHER_ID),
    CONSTRAINT FK_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID)
);

CREATE TABLE AUDIT_SUBJECT(
    SUBJECT_ID INT,
    SUBJECT_NAME VARCHAR(150),
    SUBJECT_CREDITS INT,
    SUBJECT_DEPARTMENT VARCHAR(150)
);
